// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dettacare.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Dettacare {
  /// <summary>
  ///  The greeting service definition.
  /// </summary>
  public static class UserFunction
  {
    static readonly string __ServiceName = "dettacare.UserFunction";

    static readonly Marshaller<global::Dettacare.LoginRequest> __Marshaller_LoginRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dettacare.LoginRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Dettacare.Response> __Marshaller_Response = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dettacare.Response.Parser.ParseFrom);

    static readonly Method<global::Dettacare.LoginRequest, global::Dettacare.Response> __Method_GoLogin = new Method<global::Dettacare.LoginRequest, global::Dettacare.Response>(
        MethodType.Unary,
        __ServiceName,
        "GoLogin",
        __Marshaller_LoginRequest,
        __Marshaller_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dettacare.DettacareReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserFunction</summary>
    public abstract class UserFunctionBase
    {
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Dettacare.Response> GoLogin(global::Dettacare.LoginRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserFunction</summary>
    public class UserFunctionClient : ClientBase<UserFunctionClient>
    {
      /// <summary>Creates a new client for UserFunction</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserFunctionClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserFunction that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserFunctionClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserFunctionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserFunctionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::Dettacare.Response GoLogin(global::Dettacare.LoginRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GoLogin(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual global::Dettacare.Response GoLogin(global::Dettacare.LoginRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GoLogin, null, options, request);
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::Dettacare.Response> GoLoginAsync(global::Dettacare.LoginRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GoLoginAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Sends a greeting
      /// </summary>
      public virtual AsyncUnaryCall<global::Dettacare.Response> GoLoginAsync(global::Dettacare.LoginRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GoLogin, null, options, request);
      }
      protected override UserFunctionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserFunctionClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(UserFunctionBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GoLogin, serviceImpl.GoLogin).Build();
    }

  }
}
#endregion
